"""add_portfolio_target_price_fields

Revision ID: 035e1888bea0
Revises: b9f866cb3838
Create Date: 2025-10-20 18:19:48.362238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '035e1888bea0'
down_revision: Union[str, Sequence[str], None] = 'b9f866cb3838'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolio_snapshots', sa.Column('target_price_return_eoy', sa.Numeric(precision=8, scale=4), nullable=True))
    op.add_column('portfolio_snapshots', sa.Column('target_price_return_next_year', sa.Numeric(precision=8, scale=4), nullable=True))
    op.add_column('portfolio_snapshots', sa.Column('target_price_downside_return', sa.Numeric(precision=8, scale=4), nullable=True))
    op.add_column('portfolio_snapshots', sa.Column('target_price_upside_eoy_dollars', sa.Numeric(precision=16, scale=2), nullable=True))
    op.add_column('portfolio_snapshots', sa.Column('target_price_upside_next_year_dollars', sa.Numeric(precision=16, scale=2), nullable=True))
    op.add_column('portfolio_snapshots', sa.Column('target_price_downside_dollars', sa.Numeric(precision=16, scale=2), nullable=True))
    op.add_column('portfolio_snapshots', sa.Column('target_price_coverage_pct', sa.Numeric(precision=8, scale=4), nullable=True))
    op.add_column('portfolio_snapshots', sa.Column('target_price_positions_count', sa.Integer(), nullable=True))
    op.add_column('portfolio_snapshots', sa.Column('target_price_total_positions', sa.Integer(), nullable=True))
    op.add_column('portfolio_snapshots', sa.Column('target_price_last_updated', sa.DateTime(timezone=True), nullable=True))
    op.add_column('portfolio_target_prices', sa.Column('target_upside_eoy_value', sa.Numeric(precision=16, scale=2), nullable=True))
    op.add_column('portfolio_target_prices', sa.Column('target_upside_next_year_value', sa.Numeric(precision=16, scale=2), nullable=True))
    op.add_column('portfolio_target_prices', sa.Column('target_downside_value', sa.Numeric(precision=16, scale=2), nullable=True))
    op.drop_constraint(op.f('fk_position_ir_betas_portfolio'), 'position_interest_rate_betas', type_='foreignkey')
    op.create_foreign_key(op.f('fk_position_interest_rate_betas_portfolio_id_portfolios'), 'position_interest_rate_betas', 'portfolios', ['portfolio_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_position_interest_rate_betas_portfolio_id_portfolios'), 'position_interest_rate_betas', type_='foreignkey')
    op.create_foreign_key(op.f('fk_position_ir_betas_portfolio'), 'position_interest_rate_betas', 'portfolios', ['portfolio_id'], ['id'], ondelete='CASCADE')
    op.drop_column('portfolio_target_prices', 'target_downside_value')
    op.drop_column('portfolio_target_prices', 'target_upside_next_year_value')
    op.drop_column('portfolio_target_prices', 'target_upside_eoy_value')
    op.drop_column('portfolio_snapshots', 'target_price_last_updated')
    op.drop_column('portfolio_snapshots', 'target_price_total_positions')
    op.drop_column('portfolio_snapshots', 'target_price_positions_count')
    op.drop_column('portfolio_snapshots', 'target_price_coverage_pct')
    op.drop_column('portfolio_snapshots', 'target_price_downside_dollars')
    op.drop_column('portfolio_snapshots', 'target_price_upside_next_year_dollars')
    op.drop_column('portfolio_snapshots', 'target_price_upside_eoy_dollars')
    op.drop_column('portfolio_snapshots', 'target_price_downside_return')
    op.drop_column('portfolio_snapshots', 'target_price_return_next_year')
    op.drop_column('portfolio_snapshots', 'target_price_return_eoy')
    # ### end Alembic commands ###
