"""Add company_profiles table

Revision ID: 129542220fba
Revises: bade83d52960
Create Date: 2025-10-03 22:38:18.294838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '129542220fba'
down_revision: Union[str, Sequence[str], None] = 'bade83d52960'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_profiles',
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('exchange', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=10), nullable=True),
    sa.Column('market_cap', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('is_etf', sa.Boolean(), nullable=True),
    sa.Column('is_fund', sa.Boolean(), nullable=True),
    sa.Column('ceo', sa.String(length=100), nullable=True),
    sa.Column('employees', sa.Integer(), nullable=True),
    sa.Column('website', sa.String(length=200), nullable=True),
    sa.Column('pe_ratio', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('forward_pe', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('dividend_yield', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('beta', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('week_52_high', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('week_52_low', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('target_mean_price', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('target_high_price', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('target_low_price', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('number_of_analyst_opinions', sa.Integer(), nullable=True),
    sa.Column('recommendation_mean', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('recommendation_key', sa.String(length=20), nullable=True),
    sa.Column('forward_eps', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('earnings_growth', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('revenue_growth', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('earnings_quarterly_growth', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('profit_margins', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('operating_margins', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('gross_margins', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('return_on_assets', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('return_on_equity', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('total_revenue', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('current_year_revenue_avg', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('current_year_revenue_low', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('current_year_revenue_high', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('current_year_revenue_growth', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('current_year_earnings_avg', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('current_year_earnings_low', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('current_year_earnings_high', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('current_year_end_date', sa.Date(), nullable=True),
    sa.Column('next_year_revenue_avg', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('next_year_revenue_low', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('next_year_revenue_high', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('next_year_revenue_growth', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('next_year_earnings_avg', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('next_year_earnings_low', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('next_year_earnings_high', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('next_year_end_date', sa.Date(), nullable=True),
    sa.Column('data_source', sa.String(length=50), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('symbol', name=op.f('pk_company_profiles'))
    )
    op.create_index('ix_company_profiles_symbol', 'company_profiles', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_company_profiles_symbol', table_name='company_profiles')
    op.drop_table('company_profiles')
    # ### end Alembic commands ###
