"""add_investment_classification_fields

Revision ID: 927c043e92ee
Revises: add_equity_balance
Create Date: 2025-09-18 00:05:59.463035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '927c043e92ee'
down_revision: Union[str, Sequence[str], None] = 'add_equity_balance'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('positions', sa.Column('investment_class', sa.String(length=20), nullable=True))
    op.add_column('positions', sa.Column('investment_subtype', sa.String(length=30), nullable=True))
    op.create_index('ix_positions_inv_class_subtype', 'positions', ['investment_class', 'investment_subtype'], unique=False)
    op.create_index('ix_positions_investment_class', 'positions', ['investment_class'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_positions_investment_class', table_name='positions')
    op.drop_index('ix_positions_inv_class_subtype', table_name='positions')
    op.drop_column('positions', 'investment_subtype')
    op.drop_column('positions', 'investment_class')
    # ### end Alembic commands ###
