"""add position_tags junction table

Revision ID: bade83d52960
Revises: 18252b0a1c28
Create Date: 2025-10-02 23:37:01.554253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bade83d52960'
down_revision: Union[str, Sequence[str], None] = '18252b0a1c28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('position_tags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('position_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('assigned_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], name=op.f('fk_position_tags_assigned_by_users')),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], name=op.f('fk_position_tags_position_id_positions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags_v2.id'], name=op.f('fk_position_tags_tag_id_tags_v2'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_position_tags')),
    sa.UniqueConstraint('position_id', 'tag_id', name='unique_position_tag')
    )
    op.create_index('ix_position_tags_assigned_at', 'position_tags', ['assigned_at'], unique=False)
    op.create_index('ix_position_tags_position_id', 'position_tags', ['position_id'], unique=False)
    op.create_index('ix_position_tags_tag_id', 'position_tags', ['tag_id'], unique=False)
    op.drop_index(op.f('idx_strategies_direction'), table_name='strategies')
    op.drop_index(op.f('idx_strategies_inv_class'), table_name='strategies')
    op.drop_index(op.f('idx_strategies_inv_class_direction'), table_name='strategies')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_strategies_inv_class_direction'), 'strategies', ['primary_investment_class', 'direction'], unique=False)
    op.create_index(op.f('idx_strategies_inv_class'), 'strategies', ['primary_investment_class'], unique=False)
    op.create_index(op.f('idx_strategies_direction'), 'strategies', ['direction'], unique=False)
    op.drop_index('ix_position_tags_tag_id', table_name='position_tags')
    op.drop_index('ix_position_tags_position_id', table_name='position_tags')
    op.drop_index('ix_position_tags_assigned_at', table_name='position_tags')
    op.drop_table('position_tags')
    # ### end Alembic commands ###
