"""add_fundamental_tables_and_enhance_company_profiles

Revision ID: ce3dd9222427
Revises: 9b0768a49ad8
Create Date: 2025-11-02 13:47:28.716504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ce3dd9222427'
down_revision: Union[str, Sequence[str], None] = '9b0768a49ad8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('balance_sheets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('period_date', sa.Date(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=True),
    sa.Column('fiscal_quarter', sa.Integer(), nullable=True),
    sa.Column('frequency', sa.String(length=1), nullable=False),
    sa.Column('total_assets', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('current_assets', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('cash_and_cash_equivalents', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('short_term_investments', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('accounts_receivable', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('inventory', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('property_plant_equipment', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('intangible_assets', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('total_liabilities', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('current_liabilities', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('accounts_payable', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('short_term_debt', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('long_term_debt', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('total_debt', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('total_stockholders_equity', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('retained_earnings', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('common_stock', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('working_capital', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('net_debt', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('current_ratio', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('debt_to_equity', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('book_value_per_share', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_balance_sheets')),
    sa.UniqueConstraint('symbol', 'period_date', 'frequency', name='uq_balance_symbol_period_freq')
    )
    op.create_index(op.f('ix_balance_sheets_period_date'), 'balance_sheets', ['period_date'], unique=False)
    op.create_index(op.f('ix_balance_sheets_symbol'), 'balance_sheets', ['symbol'], unique=False)
    op.create_table('cash_flows',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('period_date', sa.Date(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=True),
    sa.Column('fiscal_quarter', sa.Integer(), nullable=True),
    sa.Column('frequency', sa.String(length=1), nullable=False),
    sa.Column('operating_cash_flow', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('depreciation_and_amortization', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('stock_based_compensation', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('change_in_working_capital', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('investing_cash_flow', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('capital_expenditures', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('acquisitions', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('purchases_of_investments', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('financing_cash_flow', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('dividends_paid', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('stock_repurchases', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('debt_issuance_repayment', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('net_change_in_cash', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('beginning_cash_position', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('free_cash_flow', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('fcf_margin', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cash_flows')),
    sa.UniqueConstraint('symbol', 'period_date', 'frequency', name='uq_cashflow_symbol_period_freq')
    )
    op.create_index(op.f('ix_cash_flows_period_date'), 'cash_flows', ['period_date'], unique=False)
    op.create_index(op.f('ix_cash_flows_symbol'), 'cash_flows', ['symbol'], unique=False)
    op.create_table('income_statements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('period_date', sa.Date(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=True),
    sa.Column('fiscal_quarter', sa.Integer(), nullable=True),
    sa.Column('frequency', sa.String(length=1), nullable=False),
    sa.Column('total_revenue', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('cost_of_revenue', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('gross_profit', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('gross_margin', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('research_and_development', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('selling_general_and_administrative', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('operating_income', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('operating_margin', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('ebit', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('ebitda', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('net_income', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('net_margin', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('diluted_eps', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('basic_eps', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('basic_average_shares', sa.Integer(), nullable=True),
    sa.Column('diluted_average_shares', sa.Integer(), nullable=True),
    sa.Column('tax_provision', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('interest_expense', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('depreciation_and_amortization', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_income_statements')),
    sa.UniqueConstraint('symbol', 'period_date', 'frequency', name='uq_income_symbol_period_freq')
    )
    op.create_index(op.f('ix_income_statements_period_date'), 'income_statements', ['period_date'], unique=False)
    op.create_index(op.f('ix_income_statements_symbol'), 'income_statements', ['symbol'], unique=False)
    op.drop_index(op.f('idx_batch_run_date'), table_name='batch_run_tracking')
    op.drop_table('batch_run_tracking')
    op.add_column('company_profiles', sa.Column('current_quarter_target_period_date', sa.Date(), nullable=True))
    op.add_column('company_profiles', sa.Column('current_quarter_revenue_avg', sa.Numeric(precision=20, scale=2), nullable=True))
    op.add_column('company_profiles', sa.Column('current_quarter_revenue_low', sa.Numeric(precision=20, scale=2), nullable=True))
    op.add_column('company_profiles', sa.Column('current_quarter_revenue_high', sa.Numeric(precision=20, scale=2), nullable=True))
    op.add_column('company_profiles', sa.Column('current_quarter_eps_avg', sa.Numeric(precision=12, scale=4), nullable=True))
    op.add_column('company_profiles', sa.Column('current_quarter_eps_low', sa.Numeric(precision=12, scale=4), nullable=True))
    op.add_column('company_profiles', sa.Column('current_quarter_eps_high', sa.Numeric(precision=12, scale=4), nullable=True))
    op.add_column('company_profiles', sa.Column('current_quarter_analyst_count', sa.Integer(), nullable=True))
    op.add_column('company_profiles', sa.Column('next_quarter_target_period_date', sa.Date(), nullable=True))
    op.add_column('company_profiles', sa.Column('next_quarter_revenue_avg', sa.Numeric(precision=20, scale=2), nullable=True))
    op.add_column('company_profiles', sa.Column('next_quarter_revenue_low', sa.Numeric(precision=20, scale=2), nullable=True))
    op.add_column('company_profiles', sa.Column('next_quarter_revenue_high', sa.Numeric(precision=20, scale=2), nullable=True))
    op.add_column('company_profiles', sa.Column('next_quarter_eps_avg', sa.Numeric(precision=12, scale=4), nullable=True))
    op.add_column('company_profiles', sa.Column('next_quarter_eps_low', sa.Numeric(precision=12, scale=4), nullable=True))
    op.add_column('company_profiles', sa.Column('next_quarter_eps_high', sa.Numeric(precision=12, scale=4), nullable=True))
    op.add_column('company_profiles', sa.Column('next_quarter_analyst_count', sa.Integer(), nullable=True))
    op.add_column('company_profiles', sa.Column('fiscal_year_end', sa.String(length=5), nullable=True))
    op.add_column('company_profiles', sa.Column('fiscal_quarter_offset', sa.Integer(), nullable=True))
    op.add_column('company_profiles', sa.Column('next_earnings_date', sa.Date(), nullable=True))
    op.add_column('company_profiles', sa.Column('next_earnings_expected_eps', sa.Numeric(precision=12, scale=4), nullable=True))
    op.add_column('company_profiles', sa.Column('next_earnings_expected_revenue', sa.Numeric(precision=20, scale=2), nullable=True))
    op.add_column('company_profiles', sa.Column('fundamentals_last_fetched', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company_profiles', 'fundamentals_last_fetched')
    op.drop_column('company_profiles', 'next_earnings_expected_revenue')
    op.drop_column('company_profiles', 'next_earnings_expected_eps')
    op.drop_column('company_profiles', 'next_earnings_date')
    op.drop_column('company_profiles', 'fiscal_quarter_offset')
    op.drop_column('company_profiles', 'fiscal_year_end')
    op.drop_column('company_profiles', 'next_quarter_analyst_count')
    op.drop_column('company_profiles', 'next_quarter_eps_high')
    op.drop_column('company_profiles', 'next_quarter_eps_low')
    op.drop_column('company_profiles', 'next_quarter_eps_avg')
    op.drop_column('company_profiles', 'next_quarter_revenue_high')
    op.drop_column('company_profiles', 'next_quarter_revenue_low')
    op.drop_column('company_profiles', 'next_quarter_revenue_avg')
    op.drop_column('company_profiles', 'next_quarter_target_period_date')
    op.drop_column('company_profiles', 'current_quarter_analyst_count')
    op.drop_column('company_profiles', 'current_quarter_eps_high')
    op.drop_column('company_profiles', 'current_quarter_eps_low')
    op.drop_column('company_profiles', 'current_quarter_eps_avg')
    op.drop_column('company_profiles', 'current_quarter_revenue_high')
    op.drop_column('company_profiles', 'current_quarter_revenue_low')
    op.drop_column('company_profiles', 'current_quarter_revenue_avg')
    op.drop_column('company_profiles', 'current_quarter_target_period_date')
    op.create_table('batch_run_tracking',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('run_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('phase_1_status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('phase_2_status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('phase_3_status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('phase_1_duration_seconds', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('phase_2_duration_seconds', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('phase_3_duration_seconds', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('portfolios_processed', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('symbols_fetched', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('data_coverage_pct', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_batch_run_tracking')),
    sa.UniqueConstraint('run_date', name=op.f('uq_batch_run_tracking_run_date'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_batch_run_date'), 'batch_run_tracking', ['run_date'], unique=False)
    op.drop_index(op.f('ix_income_statements_symbol'), table_name='income_statements')
    op.drop_index(op.f('ix_income_statements_period_date'), table_name='income_statements')
    op.drop_table('income_statements')
    op.drop_index(op.f('ix_cash_flows_symbol'), table_name='cash_flows')
    op.drop_index(op.f('ix_cash_flows_period_date'), table_name='cash_flows')
    op.drop_table('cash_flows')
    op.drop_index(op.f('ix_balance_sheets_symbol'), table_name='balance_sheets')
    op.drop_index(op.f('ix_balance_sheets_period_date'), table_name='balance_sheets')
    op.drop_table('balance_sheets')
    # ### end Alembic commands ###
