"""add_portfolio_target_prices_table

Revision ID: 1dafe8c1dd84
Revises: 927c043e92ee
Create Date: 2025-09-18 00:31:06.219403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1dafe8c1dd84'
down_revision: Union[str, Sequence[str], None] = '927c043e92ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolio_target_prices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('portfolio_id', sa.UUID(), nullable=False),
    sa.Column('position_id', sa.UUID(), nullable=True),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('position_type', sa.String(length=10), nullable=True),
    sa.Column('target_price_eoy', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('target_price_next_year', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('downside_target_price', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('current_price', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('current_implied_vol', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('expected_return_eoy', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('expected_return_next_year', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('downside_return', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('position_weight', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('contribution_to_portfolio_return', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('contribution_to_portfolio_risk', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('price_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('analyst_notes', sa.Text(), nullable=True),
    sa.Column('data_source', sa.String(length=50), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_portfolio_target_prices_created_by_users')),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], name=op.f('fk_portfolio_target_prices_portfolio_id_portfolios'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], name=op.f('fk_portfolio_target_prices_position_id_positions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_portfolio_target_prices')),
    sa.UniqueConstraint('portfolio_id', 'symbol', 'position_type', name='uq_portfolio_symbol_type')
    )
    op.create_index('ix_target_prices_portfolio_id', 'portfolio_target_prices', ['portfolio_id'], unique=False)
    op.create_index('ix_target_prices_position_id', 'portfolio_target_prices', ['position_id'], unique=False)
    op.create_index('ix_target_prices_symbol', 'portfolio_target_prices', ['symbol'], unique=False)
    op.create_index('ix_target_prices_updated_at', 'portfolio_target_prices', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_target_prices_updated_at', table_name='portfolio_target_prices')
    op.drop_index('ix_target_prices_symbol', table_name='portfolio_target_prices')
    op.drop_index('ix_target_prices_position_id', table_name='portfolio_target_prices')
    op.drop_index('ix_target_prices_portfolio_id', table_name='portfolio_target_prices')
    op.drop_table('portfolio_target_prices')
    # ### end Alembic commands ###
