"""add_notes_column_and_active_positions_index

Revision ID: 2623cfc89fb7
Revises: f2a8b1c4d5e6
Create Date: 2025-11-03 12:47:55.814400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2623cfc89fb7'
down_revision: Union[str, Sequence[str], None] = 'f2a8b1c4d5e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('positions', sa.Column('notes', sa.String(), nullable=True))
    op.create_index('idx_position_portfolio_active', 'positions', ['portfolio_id', 'deleted_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_position_portfolio_active', table_name='positions')
    op.drop_column('positions', 'notes')
    # ### end Alembic commands ###
