"""Add sector exposure and concentration fields to portfolio_snapshots

Revision ID: 7003a3be89fe
Revises: f8g9h0i1j2k3
Create Date: 2025-10-19 23:09:14.165720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7003a3be89fe'
down_revision: Union[str, Sequence[str], None] = 'f8g9h0i1j2k3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ai_insight_templates', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_ai_templates_insight_type'), table_name='ai_insight_templates')
    op.create_index(op.f('ix_ai_insight_templates_insight_type'), 'ai_insight_templates', ['insight_type'], unique=False)
    op.alter_column('ai_insights', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('benchmarks_sector_weights', 'benchmark_code',
               existing_type=sa.VARCHAR(length=32),
               comment=None,
               existing_comment='Benchmark identifier (e.g., SP500)',
               existing_nullable=False)
    op.alter_column('benchmarks_sector_weights', 'asof_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Date these weights are valid for',
               existing_nullable=False)
    op.alter_column('benchmarks_sector_weights', 'sector',
               existing_type=sa.VARCHAR(length=64),
               comment=None,
               existing_comment='GICS sector name',
               existing_nullable=False)
    op.alter_column('benchmarks_sector_weights', 'weight',
               existing_type=sa.NUMERIC(precision=12, scale=6),
               comment=None,
               existing_comment='Sector weight as decimal (0.28 = 28%)',
               existing_nullable=False)
    op.alter_column('benchmarks_sector_weights', 'market_cap',
               existing_type=sa.NUMERIC(precision=20, scale=2),
               comment=None,
               existing_comment='Total market cap for sector in USD',
               existing_nullable=True)
    op.alter_column('benchmarks_sector_weights', 'num_constituents',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Number of stocks in this sector',
               existing_nullable=True)
    op.alter_column('benchmarks_sector_weights', 'data_source',
               existing_type=sa.VARCHAR(length=32),
               comment=None,
               existing_comment='Data provider (FMP, manual, etc)',
               existing_nullable=False,
               existing_server_default=sa.text("'FMP'::character varying"))
    op.alter_column('benchmarks_sector_weights', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('benchmarks_sector_weights', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('portfolio_snapshots', 'realized_volatility_21d',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               comment=None,
               existing_comment='Realized volatility over 21 trading days (~1 month)',
               existing_nullable=True)
    op.alter_column('portfolio_snapshots', 'realized_volatility_63d',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               comment=None,
               existing_comment='Realized volatility over 63 trading days (~3 months)',
               existing_nullable=True)
    op.alter_column('portfolio_snapshots', 'expected_volatility_21d',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               comment=None,
               existing_comment='HAR model forecast for next 21 trading days',
               existing_nullable=True)
    op.alter_column('portfolio_snapshots', 'volatility_trend',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Volatility direction: increasing, decreasing, stable',
               existing_nullable=True)
    op.alter_column('portfolio_snapshots', 'volatility_percentile',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               comment=None,
               existing_comment='Current volatility percentile vs 1-year history (0-1)',
               existing_nullable=True)
    op.alter_column('portfolio_snapshots', 'beta_calculated_90d',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               comment=None,
               existing_comment='Equity-weighted average of position betas',
               existing_nullable=True)
    op.alter_column('portfolio_snapshots', 'beta_calculated_90d_r_squared',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               comment=None,
               existing_comment='Weighted average R-squared from position betas',
               existing_nullable=True)
    op.alter_column('portfolio_snapshots', 'beta_calculated_90d_observations',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Minimum observations across all positions',
               existing_nullable=True)
    op.alter_column('portfolio_snapshots', 'beta_portfolio_regression',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               comment=None,
               existing_comment='Direct OLS regression of portfolio returns vs SPY (Phase 3 future work)',
               existing_nullable=True)
    op.alter_column('portfolio_snapshots', 'sector_exposure',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               comment=None,
               existing_comment='Sector weights as JSON (e.g., {"Technology": 0.35, "Healthcare": 0.18})',
               existing_nullable=True)
    op.alter_column('portfolio_snapshots', 'hhi',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=10, scale=4),
               comment=None,
               existing_comment='Herfindahl-Hirschman Index (concentration measure)',
               existing_nullable=True)
    op.alter_column('portfolio_snapshots', 'effective_num_positions',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='Effective number of positions (1/HHI)',
               existing_nullable=True)
    op.alter_column('portfolio_snapshots', 'top_3_concentration',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               comment=None,
               existing_comment='Sum of top 3 position weights',
               existing_nullable=True)
    op.alter_column('portfolio_snapshots', 'top_10_concentration',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               comment=None,
               existing_comment='Sum of top 10 position weights',
               existing_nullable=True)
    op.drop_index(op.f('idx_snapshots_beta'), table_name='portfolio_snapshots')
    op.drop_index(op.f('idx_snapshots_volatility'), table_name='portfolio_snapshots')
    op.alter_column('position_market_betas', 'beta',
               existing_type=sa.NUMERIC(precision=12, scale=6),
               comment=None,
               existing_comment='Market beta coefficient',
               existing_nullable=False)
    op.alter_column('position_market_betas', 'alpha',
               existing_type=sa.NUMERIC(precision=12, scale=6),
               comment=None,
               existing_comment='Regression intercept (alpha)',
               existing_nullable=True)
    op.alter_column('position_market_betas', 'r_squared',
               existing_type=sa.NUMERIC(precision=12, scale=6),
               comment=None,
               existing_comment='R-squared goodness of fit',
               existing_nullable=True)
    op.alter_column('position_market_betas', 'std_error',
               existing_type=sa.NUMERIC(precision=12, scale=6),
               comment=None,
               existing_comment='Standard error of beta estimate',
               existing_nullable=True)
    op.alter_column('position_market_betas', 'p_value',
               existing_type=sa.NUMERIC(precision=12, scale=6),
               comment=None,
               existing_comment='P-value for beta significance',
               existing_nullable=True)
    op.alter_column('position_market_betas', 'observations',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Number of data points in regression',
               existing_nullable=False)
    op.alter_column('position_market_betas', 'window_days',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Regression window length',
               existing_nullable=False,
               existing_server_default=sa.text('90'))
    op.alter_column('position_market_betas', 'method',
               existing_type=sa.VARCHAR(length=32),
               comment=None,
               existing_comment='Calculation method',
               existing_nullable=False,
               existing_server_default=sa.text("'OLS_SIMPLE'::character varying"))
    op.alter_column('position_market_betas', 'market_index',
               existing_type=sa.VARCHAR(length=16),
               comment=None,
               existing_comment='Market benchmark used',
               existing_nullable=False,
               existing_server_default=sa.text("'SPY'::character varying"))
    op.alter_column('position_market_betas', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('position_market_betas', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('fk_position_market_betas_portfolio_id_portfolios'), 'position_market_betas', type_='foreignkey')
    op.drop_constraint(op.f('fk_position_market_betas_position_id_positions'), 'position_market_betas', type_='foreignkey')
    op.create_foreign_key(op.f('fk_position_market_betas_portfolio_id_portfolios'), 'position_market_betas', 'portfolios', ['portfolio_id'], ['id'])
    op.create_foreign_key(op.f('fk_position_market_betas_position_id_positions'), 'position_market_betas', 'positions', ['position_id'], ['id'])
    op.alter_column('position_volatility', 'realized_vol_21d',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               comment=None,
               existing_comment='21 trading days (~1 month)',
               existing_nullable=True)
    op.alter_column('position_volatility', 'realized_vol_63d',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               comment=None,
               existing_comment='63 trading days (~3 months)',
               existing_nullable=True)
    op.alter_column('position_volatility', 'vol_daily',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               comment=None,
               existing_comment='Daily volatility component',
               existing_nullable=True)
    op.alter_column('position_volatility', 'vol_weekly',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               comment=None,
               existing_comment='Weekly (5d) volatility component',
               existing_nullable=True)
    op.alter_column('position_volatility', 'vol_monthly',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               comment=None,
               existing_comment='Monthly (21d) volatility component',
               existing_nullable=True)
    op.alter_column('position_volatility', 'expected_vol_21d',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               comment=None,
               existing_comment='HAR model forecast for next 21 trading days',
               existing_nullable=True)
    op.alter_column('position_volatility', 'vol_trend',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Volatility direction: increasing, decreasing, stable',
               existing_nullable=True)
    op.alter_column('position_volatility', 'vol_trend_strength',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               comment=None,
               existing_comment='Trend strength on 0-1 scale',
               existing_nullable=True)
    op.alter_column('position_volatility', 'vol_percentile',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               comment=None,
               existing_comment='Current volatility percentile vs 1-year history (0-1)',
               existing_nullable=True)
    op.alter_column('position_volatility', 'observations',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Number of data points used in calculation',
               existing_nullable=True)
    op.alter_column('position_volatility', 'model_r_squared',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               comment=None,
               existing_comment='HAR model R-squared goodness of fit',
               existing_nullable=True)
    op.alter_column('position_volatility', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('position_volatility', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('fk_position_volatility_position_id_positions'), 'position_volatility', type_='foreignkey')
    op.create_foreign_key(op.f('fk_position_volatility_position_id_positions'), 'position_volatility', 'positions', ['position_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_position_volatility_position_id_positions'), 'position_volatility', type_='foreignkey')
    op.create_foreign_key(op.f('fk_position_volatility_position_id_positions'), 'position_volatility', 'positions', ['position_id'], ['id'], ondelete='CASCADE')
    op.alter_column('position_volatility', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('position_volatility', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('position_volatility', 'model_r_squared',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               comment='HAR model R-squared goodness of fit',
               existing_nullable=True)
    op.alter_column('position_volatility', 'observations',
               existing_type=sa.INTEGER(),
               comment='Number of data points used in calculation',
               existing_nullable=True)
    op.alter_column('position_volatility', 'vol_percentile',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               comment='Current volatility percentile vs 1-year history (0-1)',
               existing_nullable=True)
    op.alter_column('position_volatility', 'vol_trend_strength',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               comment='Trend strength on 0-1 scale',
               existing_nullable=True)
    op.alter_column('position_volatility', 'vol_trend',
               existing_type=sa.VARCHAR(length=20),
               comment='Volatility direction: increasing, decreasing, stable',
               existing_nullable=True)
    op.alter_column('position_volatility', 'expected_vol_21d',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               comment='HAR model forecast for next 21 trading days',
               existing_nullable=True)
    op.alter_column('position_volatility', 'vol_monthly',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               comment='Monthly (21d) volatility component',
               existing_nullable=True)
    op.alter_column('position_volatility', 'vol_weekly',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               comment='Weekly (5d) volatility component',
               existing_nullable=True)
    op.alter_column('position_volatility', 'vol_daily',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               comment='Daily volatility component',
               existing_nullable=True)
    op.alter_column('position_volatility', 'realized_vol_63d',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               comment='63 trading days (~3 months)',
               existing_nullable=True)
    op.alter_column('position_volatility', 'realized_vol_21d',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               comment='21 trading days (~1 month)',
               existing_nullable=True)
    op.drop_constraint(op.f('fk_position_market_betas_position_id_positions'), 'position_market_betas', type_='foreignkey')
    op.drop_constraint(op.f('fk_position_market_betas_portfolio_id_portfolios'), 'position_market_betas', type_='foreignkey')
    op.create_foreign_key(op.f('fk_position_market_betas_position_id_positions'), 'position_market_betas', 'positions', ['position_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_position_market_betas_portfolio_id_portfolios'), 'position_market_betas', 'portfolios', ['portfolio_id'], ['id'], ondelete='CASCADE')
    op.alter_column('position_market_betas', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('position_market_betas', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('position_market_betas', 'market_index',
               existing_type=sa.VARCHAR(length=16),
               comment='Market benchmark used',
               existing_nullable=False,
               existing_server_default=sa.text("'SPY'::character varying"))
    op.alter_column('position_market_betas', 'method',
               existing_type=sa.VARCHAR(length=32),
               comment='Calculation method',
               existing_nullable=False,
               existing_server_default=sa.text("'OLS_SIMPLE'::character varying"))
    op.alter_column('position_market_betas', 'window_days',
               existing_type=sa.INTEGER(),
               comment='Regression window length',
               existing_nullable=False,
               existing_server_default=sa.text('90'))
    op.alter_column('position_market_betas', 'observations',
               existing_type=sa.INTEGER(),
               comment='Number of data points in regression',
               existing_nullable=False)
    op.alter_column('position_market_betas', 'p_value',
               existing_type=sa.NUMERIC(precision=12, scale=6),
               comment='P-value for beta significance',
               existing_nullable=True)
    op.alter_column('position_market_betas', 'std_error',
               existing_type=sa.NUMERIC(precision=12, scale=6),
               comment='Standard error of beta estimate',
               existing_nullable=True)
    op.alter_column('position_market_betas', 'r_squared',
               existing_type=sa.NUMERIC(precision=12, scale=6),
               comment='R-squared goodness of fit',
               existing_nullable=True)
    op.alter_column('position_market_betas', 'alpha',
               existing_type=sa.NUMERIC(precision=12, scale=6),
               comment='Regression intercept (alpha)',
               existing_nullable=True)
    op.alter_column('position_market_betas', 'beta',
               existing_type=sa.NUMERIC(precision=12, scale=6),
               comment='Market beta coefficient',
               existing_nullable=False)
    op.create_index(op.f('idx_snapshots_volatility'), 'portfolio_snapshots', ['portfolio_id', 'snapshot_date', 'realized_volatility_21d'], unique=False)
    op.create_index(op.f('idx_snapshots_beta'), 'portfolio_snapshots', ['portfolio_id', 'snapshot_date', 'beta_calculated_90d'], unique=False)
    op.alter_column('portfolio_snapshots', 'top_10_concentration',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               comment='Sum of top 10 position weights',
               existing_nullable=True)
    op.alter_column('portfolio_snapshots', 'top_3_concentration',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               comment='Sum of top 3 position weights',
               existing_nullable=True)
    op.alter_column('portfolio_snapshots', 'effective_num_positions',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='Effective number of positions (1/HHI)',
               existing_nullable=True)
    op.alter_column('portfolio_snapshots', 'hhi',
               existing_type=sa.Numeric(precision=10, scale=4),
               type_=sa.NUMERIC(precision=10, scale=2),
               comment='Herfindahl-Hirschman Index (concentration measure)',
               existing_nullable=True)
    op.alter_column('portfolio_snapshots', 'sector_exposure',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               comment='Sector weights as JSON (e.g., {"Technology": 0.35, "Healthcare": 0.18})',
               existing_nullable=True)
    op.alter_column('portfolio_snapshots', 'beta_portfolio_regression',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               comment='Direct OLS regression of portfolio returns vs SPY (Phase 3 future work)',
               existing_nullable=True)
    op.alter_column('portfolio_snapshots', 'beta_calculated_90d_observations',
               existing_type=sa.INTEGER(),
               comment='Minimum observations across all positions',
               existing_nullable=True)
    op.alter_column('portfolio_snapshots', 'beta_calculated_90d_r_squared',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               comment='Weighted average R-squared from position betas',
               existing_nullable=True)
    op.alter_column('portfolio_snapshots', 'beta_calculated_90d',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               comment='Equity-weighted average of position betas',
               existing_nullable=True)
    op.alter_column('portfolio_snapshots', 'volatility_percentile',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               comment='Current volatility percentile vs 1-year history (0-1)',
               existing_nullable=True)
    op.alter_column('portfolio_snapshots', 'volatility_trend',
               existing_type=sa.VARCHAR(length=20),
               comment='Volatility direction: increasing, decreasing, stable',
               existing_nullable=True)
    op.alter_column('portfolio_snapshots', 'expected_volatility_21d',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               comment='HAR model forecast for next 21 trading days',
               existing_nullable=True)
    op.alter_column('portfolio_snapshots', 'realized_volatility_63d',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               comment='Realized volatility over 63 trading days (~3 months)',
               existing_nullable=True)
    op.alter_column('portfolio_snapshots', 'realized_volatility_21d',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               comment='Realized volatility over 21 trading days (~1 month)',
               existing_nullable=True)
    op.alter_column('benchmarks_sector_weights', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('benchmarks_sector_weights', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('benchmarks_sector_weights', 'data_source',
               existing_type=sa.VARCHAR(length=32),
               comment='Data provider (FMP, manual, etc)',
               existing_nullable=False,
               existing_server_default=sa.text("'FMP'::character varying"))
    op.alter_column('benchmarks_sector_weights', 'num_constituents',
               existing_type=sa.INTEGER(),
               comment='Number of stocks in this sector',
               existing_nullable=True)
    op.alter_column('benchmarks_sector_weights', 'market_cap',
               existing_type=sa.NUMERIC(precision=20, scale=2),
               comment='Total market cap for sector in USD',
               existing_nullable=True)
    op.alter_column('benchmarks_sector_weights', 'weight',
               existing_type=sa.NUMERIC(precision=12, scale=6),
               comment='Sector weight as decimal (0.28 = 28%)',
               existing_nullable=False)
    op.alter_column('benchmarks_sector_weights', 'sector',
               existing_type=sa.VARCHAR(length=64),
               comment='GICS sector name',
               existing_nullable=False)
    op.alter_column('benchmarks_sector_weights', 'asof_date',
               existing_type=sa.DATE(),
               comment='Date these weights are valid for',
               existing_nullable=False)
    op.alter_column('benchmarks_sector_weights', 'benchmark_code',
               existing_type=sa.VARCHAR(length=32),
               comment='Benchmark identifier (e.g., SP500)',
               existing_nullable=False)
    op.alter_column('ai_insights', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_ai_insight_templates_insight_type'), table_name='ai_insight_templates')
    op.create_index(op.f('ix_ai_templates_insight_type'), 'ai_insight_templates', ['insight_type'], unique=False)
    op.alter_column('ai_insight_templates', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
